using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using RockBot.Host;

namespace Foragent.Agent;

/// <summary>
/// Seeds the operator-authored <c>sites/bsky.app/login</c> skill into the
/// configured <see cref="ISkillStore"/> on startup if it is not already
/// present. Idempotent — subsequent starts are no-ops, so recreating the
/// persistence volume does not wipe human-authored priming, but editing the
/// stored skill through another channel is preserved.
///
/// Human-authored skills seed the generalist planner with site-specific
/// primers (spec §5.6). Agent-learned skills are written by the capability
/// itself on successful task completion.
/// </summary>
internal sealed class BskySeedSkillService(
    ISkillStore skillStore,
    ILogger<BskySeedSkillService> logger) : IHostedService
{
    private const string SkillName = "sites/bsky.app/login";

    private const string SkillSummary =
        "Log in to bsky.app with an app password; look for 2FA challenges.";

    private const string SkillContent = """
        # Logging in to bsky.app

        Bluesky's public web app is at `https://bsky.app`. The login flow is
        straightforward but has a few gotchas worth knowing before you plan
        tool calls.

        ## App passwords, not account passwords

        Always authenticate with an **app password** (generated by the user
        at `https://bsky.app/settings/app-passwords`), not the account
        password. Account passwords trigger the stronger 2FA flow much more
        often, and the caller will have supplied an app-password credential
        if they intend you to log in.

        ## Login form

        The sign-in screen is reachable from the home page "Sign in" button
        or directly at `https://bsky.app/` when signed out. The form is a
        single page with two visible inputs:

        - Identifier — accepts either the handle (`rocky.bsky.social`) or a
          custom-domain handle (`rocky.lhotka.net`). **Not** the email.
        - Password — plain password field; paste the app password here.

        Submit the form by clicking the button labelled "Next" (then
        "Sign in" on the second screen once the identifier is validated).

        ## 2FA / email-code challenges

        Even with an app password, bsky occasionally prompts for an emailed
        6-digit code when signing in from a fresh context. If you see a
        screen asking for a code, stop and call `fail` — 2FA is handled by
        the caller, not by the planner. A future capability may surface
        this as an A2A `input-required` state.

        ## Composing a post after login

        The compose button is the large plus-icon floating action button on
        the home feed, or `https://bsky.app/compose`. The editor is a
        ProseMirror `contenteditable` — plain-text typing works; avoid
        pasting rich content through the tool surface.

        ## Known failure modes

        - **Rate limit / "try again later".** Space retries out; don't
          thrash on failed submits.
        - **Handle vs email.** Entering the email in the identifier field
          silently fails — re-snapshot and look for a validation message
          before assuming it worked.
        - **Stale cookie banner.** A one-time cookie banner overlays the
          sign-in button on first visit; accept it (click the "OK" or
          "Accept" button) before trying to click "Sign in".

        ## See also

        - `sites/bsky.app/compose-post` once that skill is learned.
        """;

    public async Task StartAsync(CancellationToken cancellationToken)
    {
        try
        {
            var existing = await skillStore.GetAsync(SkillName);
            if (existing is not null)
            {
                logger.LogDebug("Seed skill '{Name}' already present; leaving existing content untouched.", SkillName);
                return;
            }

            var skill = new Skill(
                Name: SkillName,
                Summary: SkillSummary,
                Content: SkillContent,
                CreatedAt: DateTimeOffset.UtcNow,
                UpdatedAt: null,
                LastUsedAt: null,
                SeeAlso: ["sites/bsky.app/compose-post"]);

            await skillStore.SaveAsync(skill);
            logger.LogInformation("Seeded human-authored skill '{Name}'.", SkillName);
        }
        catch (Exception ex)
        {
            // Seeding is a convenience — never fail the host because a seed
            // skill couldn't be written (the capability will still work
            // without it, it just loses the priming head start).
            logger.LogWarning(ex, "Failed to seed skill '{Name}'.", SkillName);
        }
    }

    public Task StopAsync(CancellationToken cancellationToken) => Task.CompletedTask;
}
